Completed design of login page and pages related to it.
xEdziu/RPG-Handy-Helper-Archived pull request #29
Opened 2024-07-28 21:30 UTC by Myjem

Together with @MANDRW we completed design of login, registrarion, resetting password and forgetting password page. 
Most likely, this page will be changed further in the future, I am aware that media-queries are still missing, but I think that the page is in a condition that allows us to continue working.

How to test it:

1. Start php server(php -S 0.0.0.0:8800 in terminal)
2. Open your browser and go to your localhost address with port provided in step above (127.0.0.1:8800)
3. Check login and registration page.
4. The link to the password reset page is on the login page.

I am waiting for your response and suggestions about visual side of things.

2024-07-28 22:18 UTC, xEdziu commented
I am not sure about the design of buttons while hovering on them. I don't feel like "shadowing" them is a good option.
Maybe we could try doing something else - like e.g. inverting colors?

2024-07-28 22:21 UTC, xEdziu commented on frontend/html/register.html
> +        <form action="">
My bad, I did not provied you guys with fileds for form, so here they are:

- username
- email
- password
- confirm password
- name
- surname
- discord tag, which should be optional field in the form

2024-07-28 22:25 UTC, xEdziu requested changes

2024-07-28 22:25 UTC, xEdziu commented on frontend/html/register.html
> +            <label for="passowrdrepeat" class="andika-bold">Repeat your password:</label>
Also all of required fields in every form should have `required` attribute, so you need to change that

2024-07-28 22:25 UTC, xEdziu commented on frontend/html/resetpassword.html
> +            <label for="resetemail" class="andika-bold">Forgot your password? Give us your email address and we will send you a link to reset your password!</label>
this text is too bulky for me. Maybe something like:
"Forgot your password? Don't worry, we will send you a link to reset it!"

2024-07-28 22:25 UTC, xEdziu commented on frontend/html/resetyourpasswordactual.html
> +        <input type="password" name="newpassword" maxlength="42" placeholder="Enter your new passowrd" class="container">
What is the purpose of `maxLength` in terms of password ?

2024-07-28 22:28 UTC, Myjem commented on frontend/html/resetyourpasswordactual.html
> +        <input type="password" name="newpassword" maxlength="42" placeholder="Enter your new passowrd" class="container">
I didn't like how passwords could go offscreen, so I added it without giving it a second thought

2024-07-28 22:28 UTC, xEdziu commented
Also, it would be nice if after every webpage title we could add `| RPG Handy Helper`, so it would look better than just plain "Login":
![image](https://github.com/user-attachments/assets/a066497a-91c0-4465-9ee4-777d80e10350)

"Login | RPG Handy Helper" would look better in my opinion

2024-07-28 23:23 UTC, xEdziu commented on frontend/html/resetyourpasswordactual.html
> +        <input type="password" name="newpassword" maxlength="42" placeholder="Enter your new passowrd" class="container">
Imo, there should be another way. I am not sure, but inputs prolly natively have scrolling if the content it to long

2024-07-28 23:24 UTC, xEdziu commented on frontend/html/resetyourpasswordactual.html
> +        <input type="password" name="newpassword" maxlength="42" placeholder="Enter your new passowrd" class="container">
and you can think of a way to view the password ("the eye")

2024-07-29 08:41 UTC, Sybirsoldat requested changes
### Good things

Landing page looks gorgeus, login, register and resetpassword pages look ok

### To Change 

I don't like the style of buttons while hovering over them, they should be change to fit more with the style of the landing page, maybe they should change color to red just like buttons on the landing page do.

### Summary

Pages look good, but as change to style of buttons should be an easy fix i will for now deny merging

2024-07-30 02:46 UTC, Myjem commented
I made few changes:

- Changed styling of buttons
- Added a way to view your password with an icon
- Fixed register page so it doesn't cut off any content
- Added a custom scrollbar(check register page)
- Fixed autofill background on login page
- Overall implemented your advices

2024-07-30 13:52 UTC, xEdziu approved these changes
All good now!

2024-07-30 13:57 UTC, Sybirsoldat approved these changes

2024-07-30 14:21 UTC, merged